# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1233, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 30, 1211, 531))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.date_Start = QtWidgets.QDateEdit(self.centralwidget)
        self.date_Start.setGeometry(QtCore.QRect(90, 0, 110, 25))
        self.date_Start.setCalendarPopup(True)
        self.date_Start.setDate(QtCore.QDate(2023, 1, 1))
        self.date_Start.setObjectName("date_Start")
        self.date_End = QtWidgets.QDateEdit(self.centralwidget)
        self.date_End.setGeometry(QtCore.QRect(290, 0, 110, 25))
        self.date_End.setCalendarPopup(True)
        self.date_End.setDate(QtCore.QDate(2024, 12, 31))
        self.date_End.setObjectName("date_End")
        self.label_Start = QtWidgets.QLabel(self.centralwidget)
        self.label_Start.setGeometry(QtCore.QRect(10, 0, 81, 21))
        self.label_Start.setObjectName("label_Start")
        self.label_End = QtWidgets.QLabel(self.centralwidget)
        self.label_End.setGeometry(QtCore.QRect(210, 0, 81, 21))
        self.label_End.setObjectName("label_End")
        self.Enter_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Enter_Button.setGeometry(QtCore.QRect(410, 0, 80, 24))
        self.Enter_Button.setObjectName("Enter_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1233, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "美國財經數據儀表板"))
        self.label_Start.setText(_translate("MainWindow", "資料起始日"))
        self.label_End.setText(_translate("MainWindow", "資料終止日"))
        self.Enter_Button.setText(_translate("MainWindow", "查詢"))
